---
- name: Install MariaDB server
  yum: 
    name: "{{ item }}"
    state: installed
  with_items:
    - mariadb-server
    - MySQL-python

#- name: Copy my.cnf
#  template: 
#    src: ~/ansible/haproxy-lamp/roles/mysql/templates/my.cnf.j2
#    dest: /etc/my.cnf
#  notify:
#    - restart_mariadb

- name: Start MariaDB
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Create DataBase
  mysql_db:
    name: "{{ database }}"
    state: present

- name: Create Users
  mysql_user:
    name: "{{ user }}"
    password: "{{ password }}"
    priv: '*.*:ALL'
    host: '%'
    state: present

- name: Allow MariaDB server through firewalld
  firewalld:
    port: "{{ mysql_port }}/tcp"
    permanent: yes
    state: enabled
...
