---
# Entrance ansible file to deploy haproxy-lamp clster.
- name: Init base environment for all hosts
hosts: all
  roles:
    - base

- name: Install HAProxy
  hosts: haproxy
  roles:
    - haproxy

- name: Install Apache and PHP
  hosts: web
  roles:
    - apache-php

- name: Install MariaDB
  hosts: mariadb
  roles:
    - mariadb
